name: Test Azure Resource Group Secret

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  test-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/setup-azurecli@v1

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # Ensure this is set up in your GitHub secrets

    - name: Display Resource Group information
      run: |
        echo "Testing resource group secret..."
        echo "Resource Group: ${{ secrets.AZURE_RESOURCE_GROUP }}"

    - name: Get Resource Group Info from Azure
      run: |
        echo "Fetching Resource Group details..."
        az group show --name ${{ secrets.AZURE_RESOURCE_GROUP }} --query "{name:name, location:location, id:id}"
